FROM alpine:3.14.0
ENV LIBRD_VER=1.7.0
WORKDIR /tmp
RUN apk add --no-cache --virtual .make-deps bash make wget git gcc g++ \
&& apk add --no-cache musl-dev zlib-dev openssl zstd-dev pkgconfig libc-dev \
&& wget https://github.com/edenhill/librdkafka/archive/v${LIBRD_VER}.tar.gz \
&& tar -xvf v${LIBRD_VER}.tar.gz \
&& cd librdkafka-${LIBRD_VER} \
&& ./configure --prefix /usr \
&& make && make install && make clean && rm -rf librdkafka-${LIBRD_VER} \
&& rm -rf v${LIBRD_VER}.tar.gz \
&& apk del .make-deps && rm -rf /tmp/
RUN export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/lib/pkgconfig/
